### PR TITLE
Firmware 7.5

### PR DESCRIPTION
**Pull request by cboulay**
Add support for Blackrock firmware 7.5. The major change is the use of 64-bit timestamps.

Along the way, I also converted some Qt calls to Qt6, and unfortunately some of these are not backwards-compatible, so we now require Qt6. Hopefully the Qt dependency can be shed entirely in the future.

One of the changes I'm not too happy with is 6924f74a299f126a9bd3fe5e4bffc8ecd2a4b576 , because such a large datagram size shouldn't be necessary. However, with the upgrade to 256+ channels, the REQCONFIGALL response is large (~1200 packets) in a short amount of time, and any hiccup at all in processing incoming packets will lead to overflow packets being dropped and the final SYSREP packet being missed, meaning the startup sequence will fail on wait timeout. A better solution would be to have a thread dedicated to just pulling packets off `recv` and then queueing them up for another thread to handle. That's a much bigger effort and will likely be superseded by other design changes.

### CODE REVIEW

**Comment by dashesy** [comment]
Couldn't you increase [`cbRECBUFFLEN`](https://github.com/CerebusOSS/CereLink/blob/e5aba2af6daae4004fa0b12827580b9f46430974/cbhwlib/cbhwlib.h#L2929) to buffer more, less chance of missing packets.

**Comment by cboulay** [comment]
It already seemed pretty large at 32MB; I'm missing packets even when there's no data transmitting, just the response to REQCONFIGALL which is, IIRC, around 300 kb. As far as I can tell, the error isn't in overflowing the receive buffer, it's due to taking too long between `recv` calls while each datagram gets processed. I can't say much more about it.

BTW, while I have you, do you know what's up with https://github.com/CerebusOSS/CereLink/blob/6fc8f6640f735dcf96ba8b9f40a1e320cdb1a174/cbhwlib/InstNetwork.cpp#L613-L619 ?

It's the exact same call, no "fake" instrument as far as I can tell.

**Comment by dashesy** [comment]
Hmm. Perhaps safe to remove, do not remember what `bLoopbackPacket` is doing. You could experiment with increasing `burstcount < 1024` to handle larger bursts perhaps

**Comment by cboulay** [comment]
Thanks but that didn't work. I think the main problem is that each individual call to `m_icInstrument.Recv` is followed by a `do... while` loop to process each cbPKT in the received datagram, which is good on its own, except that within that inner loop we have a synchronous call `ProcessIncomingPacket` which can be arbitrarily slow, delaying our next call to `Recv`.

It would be better if the calls to Recv weren't blocked by `ProcessIncomingPacket`. This would require a fairly significant change and there's a bigger better change in the works.

**Comment by dashesy** [comment]
Makes sense. At least on Linux you could increase the UDP buffer size as a workaround for now.

**Pull request merged**
